# Generated by Django 4.1.7 on 2023-02-23 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
